// TYPES AUTH
export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCEEDED = "SIGN_UP_SUCCEEDED";

export const SIGN_IN_REQUEST = "SIGN_IN_REQUEST";
export const SIGN_IN_SUCCEEDED = "SIGN_IN_SUCCEEDED";

export const SIGN_IN_WITH_GOOGLE_REQUEST = "SIGN_IN_WITH_GOOGLE_REQUEST";
export const SIGN_IN_WITH_GOOGLE_SUCCEEDED = "SIGN_IN_WITH_GOOGLE_SUCCEEDED";

export const SIGN_IN_WITH_FACEBOOK_REQUEST = "SIGN_IN_WITH_FACEBOOK_REQUEST";
export const SIGN_IN_WITH_FACEBOOK_SUCCEEDED = "SIGN_IN_WITH_FACEBOOK_SUCCEEDED";

export const SIGN_OUT_REQUEST = "SIGN_OUT_REQUEST";
export const SIGN_OUT_SUCCEEDED = "SIGN_OUT_SUCCEEDED";

export const ACTIVATE_ACCOUNT_REQUEST = "ACTIVATE_ACCOUNT_REQUEST";
export const ACTIVATE_ACCOUNT_SUCCEEDED = "ACTIVATE_ACCOUNT_SUCCEEDED";

export const CHECK_AUTH_REQUEST = "CHECK_AUTH_REQUEST";
export const CHECK_AUTH_SUCCEEDED = "CHECK_AUTH_SUCCEEDED";
export const CHECK_AUTH_FAILED = "CHECK_AUTH_FAILED";

export const CHECK_ADMIN_ROLE_SUCCEEDED = "CHECK_ADMIN_ROLE_SUCCEEDED";
export const CHECK_ADMIN_ROLE_FALSE = "CHECK_ADMIN_ROLE_FALSE";

export const GET_USER_SUCCEEDED = "GET_USER_SUCCEEDED";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";

export const UPDATE_ADMIN_REQUEST = "UPDATE_ADMIN_REQUEST";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";

// TYPES ERROR
export const GET_ERROR = "GET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

// TYPES UTIL
export const LOADING_DATA = "LOADING_DATA";
export const LOADED_DATA = "LOADED_DATA";

export const GET_TYPE_NAME_TOAST = "GET_TYPE_NAME_TOAST";

export const SHOW_TOAST_SUCCEEDED = "SHOW_TOAST_SUCCEEDED";
export const SHOW_TOAST_ERROR = "SHOW_TOAST_ERROR";

export const GET_MESSAGE_FROM_SERVER = "GET_MESSAGE_FROM_SERVER";
export const CLEAR_MESSAGE_FROM_SERVER = "CLEAR_MESSAGE_FROM_SERVER";
